# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

alias timestamp='date +%s'

export LANG=en_US.UTF-8

export EDITOR=vim

export RACK_ENV=production

#export http_proxy=http://<host>:<port>
#export https_proxy=http://<host>:<port>
#export no_proxy="localhost;127.0.0.1"

export PATH=$HOME/.rvm/rubies/default/bin:/usr/local/bin:$PATH
